### PR TITLE
fixes #271: Reducible available again, bug in validMatrixFor

### LINKED ISSUE #271: master is broken
Travis doesn't build master

### PR DESCRIPTION
**Pull request by niomaster**
I hope this fixes the master build. @raulmonti I think we should merge this one into master, so that master builds again :)

### CODE REVIEW

File: vercors/src/main/scala/vct/col/rewrite/RewriteArrayRef.scala [hunk 1]
```diff
@@ -359,7 +359,7 @@ class RewriteArrayRef(source: ProgramUnit) extends AbstractRewriter(source) {
     var rowJ: ASTNode = create.expression(StandardOperator.Subscript, matrix, quantJ0)
 
     if(seqInfo0.isCell) {
-      conditions += create.starall(quantGuard, create.expression(StandardOperator.Perm, row), quantDecls: _*)
+      conditions += create.starall(quantGuard, create.expression(StandardOperator.Perm, row, create.reserved_name(ASTReserved.ReadPerm)), quantDecls: _*)
```
Comment (raulmonti) [inline vercors/src/main/scala/vct/col/rewrite/RewriteArrayRef.scala]: What is this change doing? I can see you are asking read permissions specifically, but what was it doing before when the read permissions were not specified?
